#!/bin/sh

xrdb -merge ~/.Xresources
setxkbmap de bone

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

redshift -l 52.373920:9.735603 -b 1:.48 -t 6500:3000 &
urxvtd -q -o -f &
unclutter &
exec i3
