# Zsh options
autoload -Uz compinit
compinit
set -o vi
bindkey -v
export KEYTIMEOUT=1
setopt CORRECT
setopt HIST_IGNORE_ALL_DUPS
fpath=($ZDOTDIR/functions $fpath)
WORDCHARS=${WORDCHARS//[\/]}

# Zim
zstyle ':zim:input' double-dot-expand yes
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  # Update static initialization script if it does not exist or it's outdated, before sourcing it
  source ${ZIM_HOME}/zimfw.zsh init -q
fi
source ${ZIM_HOME}/init.zsh

# Prompt
source $HOME/.zsh/prompt.zsh

# Aliases
source $HOME/.zsh/aliases.zsh

# HistorySubstringSearch
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND=fg=green,bold

# Autosuggest completion
ZSH_AUTOSUGGEST_STRATEGY=(completion)

# Autopairs
AUTOPAIR_PAIRS=('`' '`' "'" "'" '"' '"' '{' '}' '[' ']' '(' ')')

# Highlighting
autoload -Uz spell.ch
FAST_HIGHLIGHT+=(
  chroma-git spell.ch
  chroma-gbcm spell.ch
  chroma-jumpstart chroma/-subcommand.ch
)

# Keybindings
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
zmodload -F zsh/terminfo +p:terminfo
if [[ -n ${terminfo[kcuu1]} && -n ${terminfo[kcud1]} ]]; then
  bindkey ${terminfo[kcuu1]} history-substring-search-up
  bindkey ${terminfo[kcud1]} history-substring-search-down
fi
bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

ctrl-z () {
  if [[ -n "$(jobs)" ]]; then
    BUFFER="fg"
    zle accept-line
  fi
}
zle -N ctrl-z
bindkey '^Z' ctrl-z

# Title
function __before_title { print -Pn "\e]0;${3//$'\n'/; }\a" }
function __after_title { print -Pn "\e]0;zsh %~\a" }
__after_title
precmd_functions+=(__after_title)
preexec_functions+=(__before_title)

# EDITOR and MANPAGER
if command -v nvim > /dev/null; then
  export EDITOR='nvim'
  export MANPAGER="nvim -c 'set ft=man' -"
elif command -v vim > /dev/null; then
  export EDITOR='vim'
  export MANPAGER="vim -c 'set ft=man' -"
fi

