# Zsh options
autoload -Uz compinit
compinit
set -o vi
export KEYTIMEOUT=1
setopt CORRECT
fpath=($ZDOTDIR/functions $fpath)

# Zim
source $HOME/.zsh/.zim/init.zsh

# Prompt
source $HOME/.zsh/prompt.zsh

# Aliases
source $HOME/.zsh/aliases.zsh

# HistorySubstringSearch
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND=fg=green,bold

# Autopairs
AUTOPAIR_PAIRS=('`' '`' "'" "'" '"' '"' '{' '}' '[' ']' '(' ')')

# Highlighting
autoload -Uz spell.ch
FAST_HIGHLIGHT+=(
  chroma-git spell.ch
  chroma-jumpstart chroma/-subcommand.ch
)

# Keybindings
bindkey -M vicmd $terminfo[khome] beginning-of-line
bindkey -M vicmd $terminfo[kend] end-of-line

ctrl-z () {
  if [[ -n "$(jobs)" ]]; then
    BUFFER="fg"
    zle accept-line
  fi
}
zle -N ctrl-z
bindkey '^Z' ctrl-z

# Title
function __before_title { print -Pn "\e]0;${3//$'\n'/; }\a" }
function __after_title { print -Pn "\e]0;zsh %~\a" }
__after_title
precmd_functions+=(__after_title)
preexec_functions+=(__before_title)

# EDITOR and MANPAGER
if command -v nvim > /dev/null; then
  export EDITOR='nvim'
  export MANPAGER="nvim -c 'set ft=man' -"
elif command -v vim > /dev/null; then
  export EDITOR='vim'
  export MANPAGER="vim -c 'set ft=man' -"
fi

